fix: webpack dynamic require
Error: Cannot find module '**/zoomsdk.node'
      at webpackEmptyContext (**/dist/main/webpack:/node_modules/zoom-sdk-electron/lib sync:2:1)